auth:
  secrets:
    PULSE_USERNAME: '...'
    PULSE_PASSWORD: '...'
    SENTRY_API_KEY: '...'
    TABLE_SIGNING_KEY: '...'
    TABLE_CRYPTO_KEY: '...'
    ROOT_ACCESS_TOKEN: '...'
    AZURE_ACCOUNTS: '...'
    STATSUM_API_SECRET: '...'
    STATSUM_BASE_URL: '...'
    AZURE_ACCOUNT_NAME: '...'
    AZURE_ACCOUNT_KEY: '...'
    AWS_ACCESS_KEY_ID: '...'
    AWS_SECRET_ACCESS_KEY: '...'
