defaults:
  helm:
    namespace: '...'

  aws:
    accessKeyId: '...'
    secretAccessKey: '...'
    buckets:
      private: '...'
      public: '...'
      docs: '...'
      rawDocs: '...'
      references: '...'
      schemas: '...'

  sentry:
    apiToken: '...'

  pulse:
    username: '...'
    password: '...'

  azure:
    subscriptionId: '...'
    tenantId: '...'
    authStorageAccount: '...'
