# Default values for taskcluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi

global:
  node_env: production
  debug: "* -babel -express* -body-parser* -follow-redirects  -statsum -superagent -azure:agent"
  installAll: false

queue:
  service:
    internalPort: 12345
    externalPort: 12345
    type: NodePort
    name: queue
  image:
    repository: imbstack/taskcluster-queue
    proc: web
auth:
  service:
    internalPort: 12346
    externalPort: 12346
    type: NodePort
    name: auth
  image:
    repository: imbstack/taskcluster-auth
    proc: web
